#!/usr/bin/env python3
"""Export chat posts to a deterministic SQL restore script.

The generated SQL file restores chat content in posting order so replaying it
repopulates the database smoothly.
"""

import argparse
import os
import sqlite3
from pathlib import Path

DEFAULT_DB_PATH = os.environ.get("DB_PATH", "app.db")
DEFAULT_OUTPUT_PATH = "posts_restore.sql"


def sql_literal(conn: sqlite3.Connection, value):
    """Return a SQL literal string for a Python value."""
    if value is None:
        return "NULL"
    return conn.execute("SELECT quote(?)", (value,)).fetchone()[0]


def ordered_rows(conn: sqlite3.Connection, table: str, columns: list[str]):
    order_by = "timestamp ASC, id ASC" if "timestamp" in columns else "id ASC"
    query = f"SELECT {', '.join(columns)} FROM {table} ORDER BY {order_by}"
    return conn.execute(query).fetchall()


def export_posts_sql(db_path: str, output_path: str):
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        c = conn.cursor()

        tables = ["chat_messages", "comments", "likes"]
        table_columns: dict[str, list[str]] = {}

        for table in tables:
            c.execute(f"PRAGMA table_info({table})")
            cols = [row[1] for row in c.fetchall()]
            if cols:
                table_columns[table] = cols

        lines = [
            "-- Auto-generated by export_posts_sql.py",
            "PRAGMA foreign_keys = OFF;",
            "BEGIN TRANSACTION;",
            "",
            "-- Clear current chat data before replaying saved posts.",
            "DELETE FROM likes;",
            "DELETE FROM comments;",
            "DELETE FROM chat_messages;",
            "",
            "-- Keep original IDs so comments/likes remain linked to posts.",
        ]

        for table in tables:
            columns = table_columns.get(table)
            if not columns:
                continue

            rows = ordered_rows(conn, table, columns)
            if not rows:
                continue

            column_sql = ", ".join(columns)
            for row in rows:
                values_sql = ", ".join(sql_literal(conn, row[col]) for col in columns)
                lines.append(f"INSERT INTO {table} ({column_sql}) VALUES ({values_sql});")

            lines.append("")

        lines.extend(
            [
                "-- Reset autoincrement counters to the latest restored IDs.",
                "DELETE FROM sqlite_sequence WHERE name IN ('chat_messages', 'comments', 'likes');",
                "INSERT INTO sqlite_sequence(name, seq)",
                "SELECT 'chat_messages', COALESCE(MAX(id), 0) FROM chat_messages;",
                "INSERT INTO sqlite_sequence(name, seq)",
                "SELECT 'comments', COALESCE(MAX(id), 0) FROM comments;",
                "INSERT INTO sqlite_sequence(name, seq)",
                "SELECT 'likes', COALESCE(MAX(id), 0) FROM likes;",
                "",
                "COMMIT;",
                "PRAGMA foreign_keys = ON;",
                "",
            ]
        )

    Path(output_path).write_text("\n".join(lines), encoding="utf-8")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Export chat posts/comments/likes into an ordered SQL restore script."
    )
    parser.add_argument("--db", default=DEFAULT_DB_PATH, help="Path to SQLite DB file")
    parser.add_argument(
        "--out",
        default=DEFAULT_OUTPUT_PATH,
        help="Output SQL file path (default: posts_restore.sql)",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    export_posts_sql(args.db, args.out)
    print(f"Wrote ordered post restore SQL to {args.out}")


if __name__ == "__main__":
    main()
