-- Auto-generated by export_posts_sql.py
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

-- Clear current chat data before replaying saved posts.
DELETE FROM likes;
DELETE FROM comments;
DELETE FROM chat_messages;

-- Keep original IDs so comments/likes remain linked to posts.
-- Reset autoincrement counters to the latest restored IDs.
DELETE FROM sqlite_sequence WHERE name IN ('chat_messages', 'comments', 'likes');
INSERT INTO sqlite_sequence(name, seq)
SELECT 'chat_messages', COALESCE(MAX(id), 0) FROM chat_messages;
INSERT INTO sqlite_sequence(name, seq)
SELECT 'comments', COALESCE(MAX(id), 0) FROM comments;
INSERT INTO sqlite_sequence(name, seq)
SELECT 'likes', COALESCE(MAX(id), 0) FROM likes;

COMMIT;
PRAGMA foreign_keys = ON;
